config/routes.rb
Pensionfund::Application.routes.draw do
  root :to => 'home#index'

  resources :users

  resources :job_positions

  resources :payments

  resources :employees

  resources :transfers do
    collection do
      get 'edit',
          as: 'edit',
          to: 'transfers#bulk_edit'
      put 'save',
          as: 'save',
          to: 'transfers#bulk_save'
    end
  end

  resources :property_types

  resources :companies do
    member do
      get 'payments',
          as: 'edit_payments',
          to: 'companies#bulk_edit'
      put 'payments',
          as: 'save_payments',
          to: 'companies#bulk_save'
    end
  end

  resources :contracts

  get "queries/inspector"
  get "queries/manager"

  match '/login' => 'application#authenticate', via: [:get, :post]
  match '/logout' => 'application#logout', via: [:get, :post]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :role_id
  validates_uniqueness_of :email

  def role
    User.role_name role_id
  end

  def self.role_name role_number
    case role_number
      when 0 then I18n.t "user.admin"
      when 1 then I18n.t "user.operator"
      when 2 then I18n.t "user.inspector"
      when 3 then I18n.t "user.manager"
      else raise Exception.new "Unknown role_id"
    end
  end

  def to_s
    email+': '+role
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: I18n.t('user.successfully_created') }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: I18n.t('user.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    ps = params.require(:user).permit(:password, :password_confirmation, :email, :role_id)
    ps[:email] && ps[:email].squish!
    ps
  end

  def current_resource
    @current_resource||=User.find(params[:id]) if params[:id]
  end

  helper_method  :current_resource
end

app/helpers/users_helper.rb
module UsersHelper
  def role_items
    items = []
    for r in 0..3 do
      items << [User.role_name(r), r]
    end
    items
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email,t('user.email') %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password, t('user.password') %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, t('user.password_confirmation') %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= if_param_permitted :user, :role_id do
    "<div class='field'>
      #{f.label :role_id, t('user.role')}
      #{f.select :role_id, role_items}
      </div>"
  end %>

  <div class="actions">
    <%= f.submit t('user.update')%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3><%= t('user.editing_title')%></h3>
<div class="content">
  <%= link_to t('user.show'), @user %> |
  <%= link_to t('back'), user_path %>
</div>
<%= render 'form' %>

app/views/users/index.html.erb
<h3><%= t('user.title')%></h3>
<div class="content">
  <% if permitted? :users, :new %>
    <%= link_to t('user.new'), new_user_path %>
  <% end -%>
</div>
<table class="content-table">
  <thead>
    <tr>
      <th><%= t('user.email')%></th>
      <th><%= t('user.role')%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="item-wrapper">
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <% if permitted? :users, :show, user %>
          <td><%= link_to t('user.show'), user %></td>
        <% end -%>

        <% if permitted? :users, :edit, user %>
          <td><%= link_to t('user.edit'), edit_user_path(user) %></td>
        <% end -%>

        <% if permitted? :users, :destroy, user %>
          <td><%= link_to t('user.destroy'), user, method: :delete, data: { confirm: t('are_you_sure') } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h3><%= t('position.new')%></h3>
<div class="content">
  <%= link_to t('back'), job_positions_path %>
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<h3><%= @user.email %></h3>
<div class="content">
	<% if permitted? :users, :edit, current_resource %>
  	<%= link_to t('user.edit'), edit_user_path(@user) %> |
  <% end -%>
  <%= link_to t('back'), users_path %>
</div>
<div class="content">
<p>
  <strong><%= t('user.email')%>:</strong>
  <%= @user.email %>
</p>
<p>
  <strong><%= t('user.role')%>:</strong>
  <%= @user.role %>
</p>
</div>