config/routes.rb
Pensionfund::Application.routes.draw do
  root :to => 'home#index'

  resources :users

  resources :job_positions

  resources :payments

  resources :employees

  resources :transfers do
    collection do
      get 'edit',
          as: 'edit',
          to: 'transfers#bulk_edit'
      put 'save',
          as: 'save',
          to: 'transfers#bulk_save'
    end
  end

  resources :property_types

  resources :companies do
    member do
      get 'payments',
          as: 'edit_payments',
          to: 'companies#bulk_edit'
      put 'payments',
          as: 'save_payments',
          to: 'companies#bulk_save'
    end
  end

  resources :contracts

  get "queries/inspector"
  get "queries/manager"

  match '/login' => 'application#authenticate', via: [:get, :post]
  match '/logout' => 'application#logout', via: [:get, :post]

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :property_type
  has_many :contracts
  has_many :transfers
  has_many :payments
  has_many :employees, through: :contracts
  validates_uniqueness_of :vat, :name
  validates_presence_of :name, :vat, :property_type

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @filtered = ['company']
    @contracts = @company.contracts
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html {
          redirect_to redirect_link(company_id: @company.id) ||@company, notice: t('company.successfully_created')
        }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: t('company.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  def bulk_edit
    @company = Company.find(params[:id])
    month = DateTime.now.month
    year = DateTime.now.year
    params[:date]||= { year: year, month: month }
    @payments = @company.payments.where(month: params[:date][:month], year: params[:date][:year])
    actual_payments_employee_ids = @payments.map do |p| p.employee.id end
    new_payments = @company.employees.map do |e|
      Payment.new(employee: e, month: month, year: year, amount: 0) unless
          actual_payments_employee_ids.include? e.id
    end.compact
    @payments = @payments + new_payments
  end

  def bulk_save
    year = params[:date][:year].to_i
    month = params[:date][:month].to_i
    company = Company.find(params[:id].to_i)
    begin
      params[:payments_for].each_pair do |employee, amount|
        amount = amount.to_i
        payment = Payment.where(year: year, month: month, company: company, employee_id: employee.to_i).first
        existed = !!payment
        payment||= Payment.new(year: year, month: month, company: company, employee_id: employee.to_i)
        if existed and amount == 0
          payment.destroy!
        else
          payment.amount = amount
          payment.save! unless amount == 0
        end
      end
      redirect_to edit_payments_company_path(date: { year: year, month: month }), notice: t('payment.successfully_updated')
    rescue Exception => e
      redirect_to edit_payments_company_path(date: { year: year, month: month }), alert: e.message
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      ps = params.require(:company).permit(:vat, :name, :district, :property_type, :property_type_id)
      ps[:name] && ps[:name].squish!
      ps[:district] && ps[:district].squish!
      ps
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def company_items companies = Company.all
    companies.map{|e|
      [e.name, e.id]
    }.sort!{|e1,e2|
      e1[0]<=>e2[0]
    }
  end

end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id, t('company.id') %>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :vat, t('company.vat') %>
    <%= f.number_field :vat %>
  </div>
  <div class="field">
    <%= f.label :name, t('company.name') %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :district, t('company.district') %>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :property_type_id, t('company.property_type') %>
    <%= f.select(:property_type_id, property_type_items ) %>
  </div>
  <div class="actions">
    <%= f.submit t('company.update') %>
  </div>
<% end %>

app/views/companies/bulk_edit.html.erb
<%= form_tag edit_payments_company_path, method: "GET" do%>
    <div class="field">
      <%= label :month, t('payment.month'), for: :payment_month%>
      <%= select_month(params[:date][:month].to_i, id: :month, field_name: :month) %>
    </div>

    <div class="field">
      <%= label :year, t('payment.year'), for: :payment_year %>
      <%= select_year(params[:date][:year].to_i, id: :year, field_name: :year) %>
    </div>

    <div class="actions">
      <%= submit_tag t('payment.set_date')%>
    </div>
<% end %>
<%= form_tag save_payments_company_path, method: "PUT" do%>
    <%= hidden_field_tag('date[year]', params[:date][:year])%>
    <%= hidden_field_tag('date[month]', params[:date][:month])%>
    <table class="content-table">
      <tr class="item-wrapper">
        <th><%= t('payment.employee')%></th>
        <th><%= t('payment.amount')%></th>
      </tr>
        <% @payments.each do |p| %>
        <tr>
          <td><%= p.employee%></td>
          <td><%= number_field_tag "payments_for[#{p.employee.id}]", p.amount  %></td>
        </tr>
        <% end %>
    </table>
    <% if permitted? :payments, :bulk_save %>
        <div class="actions">
          <%= submit_tag t('payment.update')%>
        </div>
    <% end %>
<% end %>

app/views/companies/edit.html.erb
<h3><%= t('company.editing_title')%></h3>
<div class="content">
  <%= link_to t('company.show'), @company %> |
  <%= link_to t('back'), companies_path %>
</div>
<%= render 'form' %>

app/views/companies/index.html.erb
<h3><%= t('company.title')%></h3>
<div class="content">
  <%= raw "<td>#{link_to t('company.new'), new_company_path}</td>" if permitted? :companies, :new %>
</div>
<table class="content-table">
  <thead>
    <tr>
      <th><%= t('company.id')%></th>
      <th><%= t('company.vat')%></th>
      <th><%= t('company.name')%></th>
      <th><%= t('company.district')%></th>
      <th><%= t('company.property_type')%></th>
      <%= raw"<th></th>" if permitted? :companies, :show %>
      <%= raw"<th></th>" if permitted? :companies, :edit %>
      <%= raw"<th></th>" if permitted? :companies, :destroy %>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr class="item-wrapper">
        <td><%= company.id %></td>
        <td><%= company.vat %></td>
        <td><%= company.name %></td>
        <td><%= company.district %></td>
        <td><%= company.property_type %></td>
        <% if permitted? :companies, :show %>
            <td><%= link_to t('company.show'), company %></td>
        <% end %>
        <% if permitted? :companies, :edit %>
            <td><%= link_to t('company.edit'), edit_company_path(company) %></td>
        <% end %>
        <% if permitted? :companies, :destroy %>
            <td> <%= link_to t('company.destroy'), company, method: :delete, data: { confirm: t('are_you_sure') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h3><%= t('company.new_title')%></h3>
<div class="content">
  <%= link_to t('back'), companies_path %>
</div>
<%= render 'form' %>

app/views/companies/show.html.erb
<h3><%= @company.name %></h3>
<div class="content">
  <% if permitted? :companies, :edit %>
  <div class="content">
    <%= link_to t('company.edit'), edit_company_path(@company) %>
  </div>
  <% end %>

  <% if permitted? :payments, :bulk_edit %>
      <div class="content">
      <%= link_to t('payment.bulk_edit'), edit_payments_company_path%>
      </div>
  <% end %>

  <% if permitted? :contracts, :new %>
  <div class="content">
    <%= link_to t('company.new_contract'), new_contract_path(
          company_id:@company.id,
          filtered:[:company])%>
  </div>
  <% end %>
</div>

<div class="content">
<p>
  <strong><%= t('company.id')%>:</strong>
  <%= @company.id %>
</p>

<p>
  <strong><%= t('company.vat')%>:</strong>
  <%= @company.vat %>
</p>

<p>
  <strong><%= t('company.name')%>:</strong>
  <%= @company.name %>
</p>

<p>
  <strong><%= t('company.district')%>:</strong>
  <%= @company.district %>
</p>

<p>
  <strong><%= t('company.property_type')%>:</strong>
  <%= @company.property_type %>
</p>
</div>

<%= render 'contracts/list' %>