config/routes.rb
Pensionfund::Application.routes.draw do
  root :to => 'home#index'

  resources :users

  resources :job_positions

  resources :payments

  resources :employees

  resources :transfers do
    collection do
      get 'edit',
          as: 'edit',
          to: 'transfers#bulk_edit'
      put 'save',
          as: 'save',
          to: 'transfers#bulk_save'
    end
  end

  resources :property_types

  resources :companies do
    member do
      get 'payments',
          as: 'edit_payments',
          to: 'companies#bulk_edit'
      put 'payments',
          as: 'save_payments',
          to: 'companies#bulk_save'
    end
  end

  resources :contracts

  get "queries/inspector"
  get "queries/manager"

  match '/login' => 'application#authenticate', via: [:get, :post]
  match '/logout' => 'application#logout', via: [:get, :post]

  

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :company
  validates_presence_of :company, :transfer_date, :amount, :month, :year
  validates :month, :inclusion => { :in => 1..12 }, :allow_nil => true
  validates :year, :inclusion => { :in => 1900..2100 }, :allow_nil => true

  def to_s
    company.name+': '+transfer_date
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy, :new]

  # GET /transfers
  # GET /transfers.json
  def index
    conditions = {}
    conditions.merge! company_id: params[:company_id] if filtered? :company
    conditions.merge! year: params[:year] if filtered? :date
    conditions.merge! month: params[:month] if filtered? :date
    @transfers = Transfer.where(conditions)
    @companies = Company.all
    @current_params = {year: params[:year],
                       month: params[:month],
                       company_id: params[:company_id]}
    self.redirect_link = url_for(@current_params.merge('filtered[company]' => filtered?(:company),
                                                       'filtered[date]' => filtered?(:date)))
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
    flash.keep
  end

  # GET /transfers/new
  def new
    flash.keep
  end

  # GET /transfers/1/edit
  def edit
    flash.keep
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to redirect_link || @transfer, notice: t('transfer.successfully_created') }
        format.json { render action: 'show', status: :created, location: @transfer }
      else
        flash.keep
        format.html { render action: 'new' }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to redirect_link || @transfer, notice: t('transfer.successfully_updated') }
        format.json { head :no_content }
      else
        flash.keep
        format.html { render action: 'edit' }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  def bulk_edit
    month = DateTime.now.month
    year = DateTime.now.year
    params[:date]||= { year: year, month: month }
    @transfers = Transfer.where(month: params[:date][:month], year: params[:date][:year])
    actual_transfers_company_ids = @transfers.map do |t| t.company.id end
    new_transfers = Company.all.map do |c|
      Transfer.new(company: c,
                   month: month,
                   year: year,
                   amount: 0,
                   transfer_date: DateTime.now
      ) unless actual_transfers_company_ids.include? c.id
    end.compact
    @transfers = @transfers + new_transfers
    @current_params = {year: params[:date][:year],
                       month: params[:date][:month]}
  end

  def bulk_save
    year = params[:date][:year].to_i
    month = params[:date][:month].to_i
    date_hash = to_date_hash params[:transfer_dates]
    begin
      params[:amounts].each_pair do |company, amount|
        company = Company.find(company)
        amount = amount.to_i
        transfer = Transfer.where(
            year: year,
            month: month,
            company: company,
            transfer_date: date_hash[company.id]
        ).first
        existed = !!transfer
        transfer||= Transfer.new(
            year: year,
            month: month,
            company: company,
            transfer_date: date_hash[company.id]
        )
        if existed and amount == 0
          transfer.destroy!
        else
          transfer.amount = amount
          transfer.save! unless amount == 0
        end
      end
      redirect_to edit_transfers_path(date: { year: year, month: month }), notice: t('transfer.successfully_updated')
    rescue Exception => e
      redirect_to edit_transfers_path(date: { year: year, month: month }), alert: e.message
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to redirect_link || transfers_url }
      format.json { head :no_content }
    end
  end

  #______PRIVATE_______#
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_transfer
    @transfer = params[:id].nil? ? Transfer.new(transfer_params) : Transfer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transfer_params
    params.require(:transfer).permit! if params[:transfer]
  end

  def to_date_hash hash
    date_parts = {}
    hash.each_pair do |key, value|
      id, date_part = key.split /(?=\()/
      date_parts[id]||={}
      date_parts[id][date_part]=value
    end
    date_hash = {}
    date_parts.each_pair do |id, parts|
      date_hash[id.to_i]=Date.parse(parts.to_a.sort.collect{|c| c[1]}.join("-") )
    end
    date_hash
  end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_id, t('transfer.company') %>
    <%= f.select(:company_id, company_items ) %>
  </div>
  <div class="field">
    <%= f.label :transfer_date, t('transfer.transfer_date') %>
    <%= f.date_select :transfer_date %>
  </div>
  <div class="field">
    <%= f.label :amount, t('transfer.amount') %>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= label :month, t('transfer.month'), for: :transfer_month%>
    <%= select_month(@transfer.month, id: :month, field_name: :month, prefix: :transfer) %>
  </div>
  <div class="field">
    <%= label :year, t('transfer.year'), for: :transfer_year %>
    <%= select_year(@transfer.year, id: :year, field_name: :year, prefix: :transfer) %>
  </div>
  <div class="actions">
    <%= f.submit t('transfer.update') %>
  </div>
<% end %>

app/views/transfers/bulk_edit.html.erb
<div class="content">
  <% if permitted? :transfers, :new %>
      <%= link_to t('transfer.new'), new_transfer_path(transfer: @current_params) %>
  <% end -%>
</div>

<%= form_tag edit_transfers_path, method: "GET" do%>
    <div class="field">
      <%= label :month, t('payment.month'), for: :payment_month%>
      <%= select_month(params[:date][:month].to_i, id: :month, field_name: :month) %>
    </div>

    <div class="field">
      <%= label :year, t('payment.year'), for: :payment_year %>
      <%= select_year(params[:date][:year].to_i, id: :year, field_name: :year) %>
    </div>

    <div class="actions">
      <%= submit_tag t('payment.set_date')%>
    </div>
<% end %>

<%= form_tag save_transfers_path, method: "PUT" do%>
    <%= hidden_field_tag('date[year]', params[:date][:year])%>
    <%= hidden_field_tag('date[month]', params[:date][:month])%>
    <table class="content-table">
      <tr class="item-wrapper">
        <th><%= t('transfer.company')%></th>
        <th><%= t('transfer.transfer_date')%></th>
        <th><%= t('transfer.amount')%></th>
      </tr>
        <% @transfers.each do |t| %>
        <tr>
          <td><%= t.company%></td>
          <td><%= date_select 'transfer_dates', "#{t.company.id}", default: t.transfer_date%></td>
          <td><%= number_field_tag "amounts[#{t.company.id}]", t.amount  %></td>
        </tr>
        <% end %>
    </table>
    <% if permitted? :transfers, :bulk_save %>
        <div class="actions">
          <%= submit_tag t('transfer.update')%>
        </div>
    <% end %>
<% end %>

app/views/transfers/edit.html.erb
<h3><%= t('transfer.editing_title')%></h3>
<div class="content">
  <%= link_to t('transfer.show'), @transfer %> |
  <%= link_to t('back'), transfers_path %>
</div>

<%= render 'form' %>

app/views/transfers/index.html.erb
<h3><%= t('transfer.title')%></h3>
<div class="content">
  <% if permitted? :transfers, :new %>
    <%= link_to t('transfer.new'), new_transfer_path(transfer: @current_params) %>
  <% end -%>
</div>
<div class="content">
  <% if permitted? :transfers, :bulk_edit %>
    <%= link_to t('transfer.bulk_edit'), edit_transfers_path %>
  <% end -%>
</div>

<!-- FILTERS-->
<%= form_tag transfers_path, method: :get do %>

    <!--COMPANY FIELD-->
    <div class="field">
      <%= label_tag :company_id, t('transfer.company_filter_value'), for: :company_id  %>
      <%= select_tag :company_id, options_from_collection_for_select(@companies, \
                     :id, :name, selected: params[:company_id]), id: :company_id %>
    </div>

    <!--DATE FIELDS-->
    <div class="field">
      <%= label :month, t('transfer.month_filter_value'), for: :month%>
      <%= select_month(params[:month].to_i||DateTime.now, id: :month, prefix: 'month', discard_type: true) %>
    </div>

    <div class="field">
      <%= label :year, t('transfer.year_filter_value'), for: :year %>
      <%= select_year(params[:year].to_i||DateTime.now, id: :year, prefix: 'year', discard_type: true) %>
    </div>

    <!--COMPANY CHECKBOX-->
    <div class="field">
      <%= label_tag :company_filter, t('transfer.company_filter'), for: 'company_filter' %>
      <%= check_box_tag "filtered[]", 'company', filtered?(:company), id:'company_filter' %>
    </div>

    <!--DATE CHECKBOX-->
    <div class="field">
    <%= label_tag :date_filter, t('transfer.date_filter'), for: 'date_filter' %>
    <%= check_box_tag "filtered[]", 'date', filtered?(:date), id:'date_filter' %>
    </div>

    <div class="actions">
      <%= submit_tag t('transfer.apply_filter') %>
    </div>
<% end %>

<!--TRANSFER LIST-->
<table class="content-table">
  <thead>
    <tr>
      <th><%= t('transfer.company')%></th>
      <th><%= t('transfer.transfer_date')%></th>
      <th><%= t('transfer.amount')%></th>
      <th><%= t('transfer.month')%></th>
      <th><%= t('transfer.year')%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr class="item-wrapper">
        <td><%= transfer.company %></td>
        <td><%= transfer.transfer_date %></td>
        <td><%= transfer.amount %></td>
        <td><%= transfer.month %></td>
        <td><%= transfer.year %></td>

        <% if permitted? :transfers, :show %>
        <td><%= link_to t('transfer.show'), transfer_path(transfer) %></td>
        <% end -%>

        <% if permitted? :transfers, :edit %>
        <td><%= link_to t('transfer.edit'), edit_transfer_path(transfer) %></td>
        <% end -%>

        <% if permitted? :transfers, :destroy %>
        <td><%= link_to t('transfer.destroy'), transfer_path(transfer), \
                        method: :delete, data: { confirm: t('are_you_sure') } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transfers/new.html.erb
<h3><%= t('transfer.new_title')%></h3>
<div class="content">
  <%= link_to t('back'), transfers_path %>
</div>
<%= render 'form' %>

app/views/transfers/show.html.erb
<h3><%= @transfer.company %></h3>
<div class="content">
  <% if permitted? :transfers, :edit %>
    <%= link_to t('transfer.edit'), edit_transfer_path(@transfer) %> |
  <% end -%>
  <%= link_to t('back'), transfers_path %>
</div>
<p>
  <strong><%= t('transfer.company')%>:</strong>
  <%= @transfer.company %>
</p>

<p>
  <strong><%= t('transfer.transfer_date')%>:</strong>
  <%= @transfer.transfer_date %>
</p>

<p>
  <strong><%= t('transfer.amount')%>:</strong>
  <%= @transfer.amount %>
</p>

<p>
  <strong><%=t('transfer.date')%>:</strong>
  <%= (t('date.month_names')[@transfer.month || 0]).to_s+' '+(@transfer.year || '').to_s %>
</p>