config/routes.rb
Pensionfund::Application.routes.draw do
  root :to => 'home#index'

  resources :users

  resources :job_positions

  resources :payments

  resources :employees

  resources :transfers do
    collection do
      get 'edit',
          as: 'edit',
          to: 'transfers#bulk_edit'
      put 'save',
          as: 'save',
          to: 'transfers#bulk_save'
    end
  end

  resources :property_types

  resources :companies do
    member do
      get 'payments',
          as: 'edit_payments',
          to: 'companies#bulk_edit'
      put 'payments',
          as: 'save_payments',
          to: 'companies#bulk_save'
    end
  end

  resources :contracts

  get "queries/inspector"
  get "queries/manager"

  match '/login' => 'application#authenticate', via: [:get, :post]
  match '/logout' => 'application#logout', via: [:get, :post]

  

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="keeper">
    <div class="left">
      <%= raw t 'footer.about' %>
    </div>
    <div class="left offset100">
      <%= raw t 'footer.versions' %>:
      <%= link_to t('menu.ru'), url_for(locale: 'ru') %>
      <%= link_to t('menu.en'), url_for(locale: 'en') %>
    </div>
    <div class="right">
      <%= raw t 'footer.authors' %>
    </div>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<header>
  <div class="keeper inner">
  <div class="keeper">
    <div class="left">
      <!--<a href="<%= link_to t('menu.home') %>"><img class="logo" src="<%= asset_path('logo.gif') %>" /></a>-->
      <%= link_to image_tag( asset_path('logo.gif')), root_path, class: 'logo' %>
    </div>
    <div class="right menu">
      <ul class="main-menu">
        <li class="user">
          <% if current_user %>
              <strong><%= current_user.email%></strong>
              <%=form_tag('/logout', method: 'get') do %>
                  <%= submit_tag(t('menu.log_out'), class: 'mini-button') %>
              <% end %>
          <% else %>
              <strong><a id="login-link" href="#login-form"><%= t('menu.sign_in') %></a></strong>
              <div id="login-form">
                  <%=form_tag('/login', method: 'get', :class => 'disable_on_submit') do %>
                      <%= label_tag(:email, t('menu.email')) %>
                      <%= text_field_tag(:email) %>
                      <%= label_tag(:password, t('menu.password')) %>
                      <%= text_field_tag(:password) %>
                      <%= submit_tag(t'menu.sign_in') %>
                  <% end %>
              </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
    <div class="keeper main-menu-offset">
  <ul class="main-menu">
    <!--<li><%= link_to t('menu.home'), root_path %></li> CLICK ON IMAGE INSTEAD-->
    <% if permitted? :employees, :index %>
    <li><%= link_to t('menu.employees'), employees_path %></li>
    <% end %>

    <% if permitted? :companies, :index %>
    <li><%= link_to t('menu.companies'), companies_path %></li>
    <% end %>

    <% if permitted? :transfers, :index %>
    <li><%= link_to t('menu.transfers'), transfers_path %></li>
    <% end %>

    <% if permitted? :payments, :index %>
    <li><%= link_to t('menu.payments'), payments_path %></li>
    <% end %>

    <% if permitted? :contracts, :index %>
    <li><%= link_to t('menu.contracts'), contracts_path %></li>
    <% end %>

    <% if permitted? :property_types, :index %>
    <li><%= link_to t('menu.property_types'), property_types_path %></li>
    <% end %>

    <% if permitted? :job_positions, :index %>
    <li><%= link_to t('menu.job_positions'), job_positions_path %></li>
    <% end %>

    <% if permitted? :users, :index %>
    <li><%= link_to t('menu.users'), users_path %></li>
    <% end %>

    <% if permitted? :queries, :inspector %>
    <li><%= link_to t('menu.inspector'), queries_inspector_path %></li>
    <% end %>

    <% if permitted? :queries, :manager %>
    <li><%= link_to t('menu.manager'), queries_manager_path %></li>
    <% end %>
  </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pensionfund</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/menu' %>
<section>
  <div class="keeper inner">
    <div class="content">
      <% if notice %>
        <div id="notice"><%= notice %></div>
      <% end -%>
      <% if alert %>
        <div id="alert"><%= alert %></div>
      <% end -%>
    </div>
    <%= yield %>
</div>
    </section>
</body>
<%= render 'layouts/footer' %>
</html>